version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  api-cep-tempo:
    build:
      context: ./api-cep-tempo
      dockerfile: Dockerfile
    environment:
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - zipkin

  api-ceptempo-consumer:
    build:
      context: ./api-ceptempo-consumer
      dockerfile: Dockerfile
    environment:
      - API_CEP_TEMPO_URL=http://api-cep-tempo:8080/cep
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - api-cep-tempo
      - zipkin